### COUNT MATRIX CREATION
#### Alignment files are concatenated into a matrix

In [60]:
import os
import numpy as np
from numpy import isneginf
import pandas as pd
import glob
import sys
import csv
import re

In [61]:
path = 'STAR_Results/Gene_counts/' 

files = glob.glob(os.path.join(path , "*.tab"))

In [62]:
filenames=[]
for filename in files:
    filename=filename.split('/')[2].split('.tab')[0]
    filenames.append(filename)

In [63]:
filenames

['C_48h_A5_S11',
 'AF_48h_FAC_72h_A27_S15',
 'CHIR0.5_72h_A11_S11',
 'AF_48h_CHIR_72h_A22_S10',
 'CHIR_120h_ControlR1_S44',
 'AF_48h_CHIR_72h_A23_S11',
 'C_48h_A4_S10',
 'AF3_120h_AF3R1_S45',
 'CHIR3_72h_A10_S3',
 'CHIR20_60h_A6_S6',
 'XAV_AF3_120h_A2_S27',
 'DMSO20_72h_A20_S8',
 'DMSO3_72h_A14_S6',
 'CHIR0.5_72h_A10_S10',
 'DMSO3_72h_A13_S2',
 'CHIR0.5_72h_A12_S12',
 'C_48h_A6_S12',
 'DMSO0.5_72h_A8_S8',
 'AF_48h_FAC_72h_A25_S13',
 'CHIR_120h_A1_S26',
 'AF_48h_FAC_72h_A26_S14',
 'T_0h_A3_S9',
 'EPI_T0h_A5_S29',
 'CHIR_120h_ControlR2_S47',
 'AF_48h_A8_S14',
 'DMSO0.5_72h_A9_S9',
 'DMSO20_72h_A21_S9',
 'AF_48h_A7_S13',
 'DMSO20_72h_A19_S7',
 'XAV_AF3_120h_AF3XAV_S46',
 'CHIR3_72h_A12_S5',
 'T_0h_A2_S8',
 'CHIR20_72h_A16_S4',
 'DMSO0.5_72h_A7_S7',
 'XAV_AF3_120h_AF3XAV_S49',
 'CHIR20_72h_A17_S5',
 'AF3_120h_AF3R2_S48',
 'CHIR20_72h_A18_S6',
 'CHIR3_60h_A3_S3',
 'DMSO3_72h_A13_S13',
 'AF_48h_A9_S15',
 'DMSO3_72h_A15_S3',
 'EPI_T0h_A7_S31',
 'EPI_T0h_A6_S30',
 'CHIR3_72h_A11_S4',
 'CHIR3_60h_A2_S2',
 'AF3_120h_A4_S28',
 'CHIR20_60h_A4_S4',
 'CHIR3_60h_A1_S1',
 'CHIR20_60h_A5_S5',
 'T_0h_A1_S2',
 'CHIR3_72h_A14_S14',
 'AF_48h_CHIR_72h_A24_S12']

In [64]:
metadata=pd.read_csv('Data/metadata_andre.csv')
metadata[:5]

   Unnamed: 0            ID   Sample Condition  Batch
0           0    T_0h_A1_S2   T_0h_1      T_0h      1
1           1    T_0h_A2_S8   T_0h_2      T_0h      2
2           2    T_0h_A3_S9   T_0h_3      T_0h      3
3           3  C_48h_A4_S10  C_48h_1     C_48h      1
4           4  C_48h_A5_S11  C_48h_2     C_48h      2

In [65]:
order=metadata['ID'].to_list()
order

['T_0h_A1_S2',
 'T_0h_A2_S8',
 'T_0h_A3_S9',
 'C_48h_A4_S10',
 'C_48h_A5_S11',
 'C_48h_A6_S12',
 'AF_48h_A7_S13',
 'AF_48h_A8_S14',
 'AF_48h_A9_S15',
 'CHIR3_72h_A10_S3',
 'CHIR3_72h_A11_S4',
 'CHIR3_72h_A12_S5',
 'DMSO3_72h_A13_S2',
 'DMSO3_72h_A14_S6',
 'DMSO3_72h_A15_S3',
 'CHIR20_72h_A16_S4',
 'CHIR20_72h_A17_S5',
 'CHIR20_72h_A18_S6',
 'DMSO20_72h_A19_S7',
 'DMSO20_72h_A20_S8',
 'DMSO20_72h_A21_S9',
 'AF_48h_CHIR_72h_A22_S10',
 'AF_48h_CHIR_72h_A23_S11',
 'AF_48h_CHIR_72h_A24_S12',
 'AF_48h_FAC_72h_A25_S13',
 'AF_48h_FAC_72h_A26_S14',
 'AF_48h_FAC_72h_A27_S15',
 'EPI_T0h_A5_S29',
 'EPI_T0h_A6_S30',
 'EPI_T0h_A7_S31',
 'AF3_120h_AF3R1_S45',
 'AF3_120h_AF3R2_S48',
 'AF3_120h_A4_S28',
 'XAV_AF3_120h_AF3XAV_S46',
 'XAV_AF3_120h_AF3XAV_S49',
 'XAV_AF3_120h_A2_S27',
 'CHIR_120h_ControlR1_S44',
 'CHIR_120h_ControlR2_S47',
 'CHIR_120h_A1_S26',
 'CHIR3_60h_A1_S1',
 'CHIR3_60h_A2_S2',
 'CHIR3_60h_A3_S3',
 'CHIR20_60h_A4_S4',
 'CHIR20_60h_A5_S5',
 'CHIR20_60h_A6_S6',
 'DMSO0.5_72h_A7_S7',
 'DMSO0.5_72h_A8_S8',
 'DMSO0.5_72h_A9_S9',
 'CHIR0.5_72h_A10_S10',
 'CHIR0.5_72h_A11_S11',
 'CHIR0.5_72h_A12_S12',
 'DMSO3_72h_A13_S13',
 'CHIR3_72h_A14_S14']

In [66]:
# set order using metadata
order=metadata['ID'].to_list()

sorted_files=sorted(filenames, key=lambda x: order.index(x))
sorted_files[:5]

['T_0h_A1_S2', 'T_0h_A2_S8', 'T_0h_A3_S9', 'C_48h_A4_S10', 'C_48h_A5_S11']

In [67]:
li = []
samples =[]

#files=sorted(files, key=multiple_sort)

for filename in sorted_files:
    df = pd.read_csv('STAR_Results/Gene_counts/'+filename+'.tab', index_col=0, header=0, sep='\t', skiprows=3)
    df = df.iloc[:,1]

    li.append(df)

counts = pd.concat(li, axis=1, ignore_index=True)
counts = counts.loc[~(counts==0).all(axis=1)]
counts.columns = metadata['Sample']
counts.index.name = 'Gene_id'
counts = counts.fillna(0)


# save df
counts.to_csv(path + 'counts_chir_af_project.csv')
counts

Sample,T_0h_1,T_0h_2,T_0h_3,C_48h_1,C_48h_2,C_48h_3,AF_48h_1,AF_48h_2,AF_48h_3,CHIR3_72h_1,...,CHIR20_60h_2,CHIR20_60h_3,DMSO0.5_72h_1,DMSO0.5_72h_2,DMSO0.5_72h_3,CHIR0.5_72h_1,CHIR0.5_72h_2,CHIR0.5_72h_3,DMSO3_72h_4,CHIR3_72h_4
Gene_id,,,,,,,,,,,,,,,,,,,,,
Xkr4,0,2,0,6,2,9,6,23,13,34,...,19,16,9,13,28,25,9,39,43,35
Gm18956,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Gm37180,0,0,0,1,0,0,4,1,0,2,...,3,0,2,4,5,3,4,3,4,2
Gm37363,0,1,0,0,0,5,2,5,2,10,...,18,11,4,7,9,4,2,13,28,5
Gm37686,0,0,4,1,0,2,0,0,0,3,...,0,0,2,0,0,1,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
CAAA01147332.1,0,0,0,0,0,2,0,0,0,0,...,0,1,2,1,1,0,0,1,0,3
AC163611.1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AC140365.1,1,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
AC133095.2,3,3,4,2,0,0,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
AC149090.1,1118,803,1071,760,557,712,923,698,1024,1118,...,1580,1250,594,518,497,685,551,1138,653,771